export const customFonts = [
  { label: "Sans Serif", value: "sans-serif" },
  { label: "Arial", value: "arial" },
  { label: "Averia Libre", value: "averia-libre" },
  { label: "Calibri", value: "calibri" },
  { label: "Caveat", value: "caveat" },
  { label: "Courier Prime", value: "courier-prime" },
  { label: "Dancing Script", value: "dancing-script" },
  { label: "Grandstander", value: "grandstander" },
  { label: "Helvetica", value: "helvetica" },
  { label: "Helvetica Neue", value: "helvetica-neue" },
  { label: "Josefin Sans", value: "josefin-sans" },
  { label: "Lato", value: "lato" },
  { label: "Merriweather", value: "merriweather" },
  { label: "Montserrat", value: "montserrat" },
  { label: "Moon dance", value: "moon-dance" },
  { label: "Noto Sans", value: "noto-sans" },
  { label: "Noto Sans JP", value: "noto-sans-jp" },
  { label: "Noto Serif JP", value: "noto-serif-jp" },
  { label: "Open Sans", value: "open-sans" },
  { label: "Poppins", value: "poppins" },
  { label: "ProximaNova", value: "proximanova" },
  { label: "Quicksand", value: "quicksand" },
  { label: "Roboto", value: "roboto" },
  { label: "Rokkitt", value: "rokkitt" },
  { label: "Rowdies", value: "rowdies" },
  { label: "Source Sans Pro", value: "source-sans-pro" },
  { label: "Space mono", value: "space-mono" },
  { label: "Ubuntu", value: "ubuntu" },
];
